version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: movie_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie-network

  backend:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: movie_management
      PORT: 3001
      NODE_ENV: development
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - movie-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  movie-network:
    driver: bridge
